sudo: required

language: python

python: 3.7

before_install:
  - echo "updating ..."
  - sudo apt-get update
  - echo "installing make ..."
  - sudo apt-get install make
  - echo "installing pytest ..."
  - pip install pytest
  - echo "build iprange ..."

script:
  - make build

after_success:
  - echo "tested and built $TRAVIS_BRANCH"

notifications:
  email:
    - reut.sharabani@gmail.com
