sudo: required

language: python

before_install:
  - echo "Build iprange"

script:
  - make build

after_success:
  - echo "tested and built $TRAVIS_BRANCH"

notifications:
  email:
    - reut.sharabani@gmail.com
